/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.awt.List;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication3.mainJFrame.conn;
import static javaapplication3.mainJFrame.m;

/**
 *
 * @author nina
 */
 
public class F1 extends javax.swing.JFrame {
    static ArrayList<Integer> kitaplar = new ArrayList<>();
    static ArrayList<Integer> miktarlar = new ArrayList<>();
    /**
     * Creates new form F1
     */
      public F1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        musteriEkle = new javax.swing.JButton();
        musteriBilgileriDuzenle = new javax.swing.JButton();
        musterilistele = new javax.swing.JButton();
        personelolarak = new javax.swing.JLabel();
        siparisekleme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        musteriEkle.setText("Müşteri Ekle");
        musteriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriEkleActionPerformed(evt);
            }
        });

        musteriBilgileriDuzenle.setText("Müşteri Bilgileri Düzenle");
        musteriBilgileriDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriBilgileriDuzenleActionPerformed(evt);
            }
        });

        musterilistele.setText("Müşteri Listeleme");
        musterilistele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musterilisteleActionPerformed(evt);
            }
        });

        siparisekleme.setText("Sipariş Ekleme");
        siparisekleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sipariseklemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(siparisekleme, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(musteriBilgileriDuzenle, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(musterilistele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(musteriEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(personelolarak, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(musteriEkle)
                .addGap(18, 18, 18)
                .addComponent(musteriBilgileriDuzenle)
                .addGap(27, 27, 27)
                .addComponent(musterilistele)
                .addGap(18, 18, 18)
                .addComponent(siparisekleme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout)
                    .addComponent(personelolarak, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        try {
            personelolarak.setText("");
            conn.close();
            dispose();
            m.getUs().setText("");
            m.getPAs().setText("");
            m.setVisible(true);
            miktarlar.clear();
            kitaplar.clear();
            personelolarak.setText("");
                        } catch (SQLException ex) {
            Logger.getLogger(F1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void musteriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriEkleActionPerformed
         try {
              ResultSet rsmu=null;
              PreparedStatement pstmu=null;
              int i = 0;
              pstmu= conn.prepareStatement("select is_musteri()");
              rsmu= pstmu.executeQuery();
              while(rsmu.next()){
                  i= rsmu.getInt(1);
              }
              
              if (i!=1&& i!=2){
                   
        dispose();
        new MusteriEkle().setVisible(true);}
              else
                  personelolarak.setText("Yetkiniz Yok!");
          } catch (SQLException ex) {
              Logger.getLogger(F1.class.getName()).log(Level.SEVERE, null, ex);
          }
       // TODO add your handling code here:
    }//GEN-LAST:event_musteriEkleActionPerformed

    private void musteriBilgileriDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriBilgileriDuzenleActionPerformed
         try {
              ResultSet rsmu=null;
              PreparedStatement pstmu=null;
              int i = 0;
              pstmu= conn.prepareStatement("select is_musteri()");
              rsmu= pstmu.executeQuery();
              while(rsmu.next()){
                  i= rsmu.getInt(1);
              }
              
              if (i!=2){
                  dispose();
        new MusteriBilgileriDuzenle().setVisible(true);}
              else
                  personelolarak.setText("Yetkiniz Yok!");
          } catch (SQLException ex) {
              Logger.getLogger(F1.class.getName()).log(Level.SEVERE, null, ex);
          }
        
            
    }//GEN-LAST:event_musteriBilgileriDuzenleActionPerformed

    private void musterilisteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musterilisteleActionPerformed
          try {
              ResultSet rsmu=null;
              PreparedStatement pstmu=null;
              int i = 0;
              pstmu= conn.prepareStatement("select is_musteri()");
              rsmu= pstmu.executeQuery();
              while(rsmu.next()){
                  i= rsmu.getInt(1);
              }
              
              if (i!=1){
                  dispose();
                  new MusteriListele().setVisible(true);}
              else
                  personelolarak.setText("Yetkiniz Yok!");
          } catch (SQLException ex) {
              Logger.getLogger(F1.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_musterilisteleActionPerformed

    private void sipariseklemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sipariseklemeActionPerformed
        try {
              ResultSet rsmu=null;
              PreparedStatement pstmu=null;
              int i = 0;
              pstmu= conn.prepareStatement("select is_musteri()");
              rsmu= pstmu.executeQuery();
              while(rsmu.next()){
                  i= rsmu.getInt(1);
              }
              
              if (i!=2){
       dispose();
        new SiparisEkle().setVisible(true);}
              else
                  personelolarak.setText("Yetkiniz Yok!");
          } catch (SQLException ex) {
              Logger.getLogger(F1.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_sipariseklemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logout;
    private javax.swing.JButton musteriBilgileriDuzenle;
    private javax.swing.JButton musteriEkle;
    private javax.swing.JButton musterilistele;
    private javax.swing.JLabel personelolarak;
    private javax.swing.JButton siparisekleme;
    // End of variables declaration//GEN-END:variables
}
