/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javaapplication3.mainJFrame.conn;
import static javaapplication3.mainJFrame.m;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.AWTEvent;
import java.util.Iterator;
import static javaapplication3.F1.kitaplar;
import static javaapplication3.F1.miktarlar;
/**
 *
 * @author nina
 */
public class SiparisEkle extends javax.swing.JFrame {

    /**
     * Creates new form SiparisEkle
     */DefaultTableModel dtm;
    public SiparisEkle() {
        initComponents();
        
            dtm = (DefaultTableModel)tablo1.getModel();
        try {    dtm.setRowCount(0);
            String query2 = null;
            query2 = "SELECT * FROM kitaplar order by isim ";
            try (PreparedStatement pst = conn.prepareStatement(query2)) {
                 
                ResultSet r2 = pst.executeQuery();
                while (r2.next()){
                    String id = r2.getString(1);
                    String name = r2.getString(2);
                    String  mail = r2.getString(3);
                    
                    Object[] satir ={id, name, mail,null};
                    
                    dtm.addRow(satir);}
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
       
        //this.setisbnn(Integer.parseInt(dtm.getValueAt(isbn, 0).toString()));
        
        //String isimm = dtm.getValueAt(isbn, 1).toString();
        //int fiyatt = Integer.parseInt(dtm.getValueAt(isbn, 2).toString());
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablo1 = new javax.swing.JTable();
        miktar = new javax.swing.JTextField();
        onay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        tisbn = new javax.swing.JTextField();
        ekle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tablo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ISBN", "Kitap", "Birim Fiyat"
            }
        ));
        tablo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablo1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo1);

        onay.setText("Onay");
        onay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onayActionPerformed(evt);
            }
        });

        jLabel1.setText("Miktar");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(onay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(onay)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onayActionPerformed
       String query4 = null;
      
        String query3 ="select mid from musteri where email like '"+m.getpass()+"'";
        try (PreparedStatement pst = conn.prepareStatement(query3)) {
                ResultSet r2 = pst.executeQuery();
                String midd=null;
                while (r2.next()){
                     midd = r2.getString(1);
                } 
        
                System.out.println(query3);
           
           String query = "insert into siparis(musteri) values ("+midd+" )"+" returning sipariss";
    
       try (PreparedStatement pst1 = conn.prepareStatement(query)) {
                ResultSet r3 = pst1.executeQuery();
                int sipariss;
                while (r3.next()){
                     sipariss = Integer.parseInt(r3.getString(1));
                     setsiparis(sipariss);
                }
             int c=miktarlar.size();
              
                     for (int counter = 0; counter < c; counter++) { 
                         System.out.println("bas"+counter);
                  
                query4 ="insert into kitap_siparisi(sip,isbn,miktar) values("+getsiparis()+","+kitaplar.get(counter)+","+miktarlar.get(counter) +")";
                System.out.println(query4);
                    try (PreparedStatement pst3 = conn.prepareStatement(query4)) {
                        boolean r4 = pst3.execute();
                        pst3.close();
                        
                    }
                  
                System.out.println(counter);
      }   	
               miktarlar.clear();
                    kitaplar.clear();
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        } 
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        } 
    }//GEN-LAST:event_onayActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
dispose();
        new F1().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
        //String isimm = dtm.getValueAt(isbn, 1).toString();
        //int fiyatt = Integer.parseInt(dtm.getValueAt(isbn, 2).toString());
         // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tablo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo1MouseClicked
        dtm = (DefaultTableModel)tablo1.getModel();
        int  SelectedRowIndex= tablo1.getSelectedRow();
       this.setisbnn(Integer.parseInt((String) dtm.getValueAt(SelectedRowIndex, 0)));
        System.out.println(getisbnn());
       tisbn.setText((String) dtm.getValueAt(SelectedRowIndex, 0));
       kitaplar.add(getisbnn());
       
    }//GEN-LAST:event_tablo1MouseClicked

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        miktarlar.add(Integer.parseInt(miktar.getText()));
        miktar.setText("");
        tisbn.setText("");
    }//GEN-LAST:event_ekleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisEkle().setVisible(true);
            }
        });
    }
  public Integer getisbnn() {
		return isbnn;
	}

	public void setisbnn(Integer a) {
		this.isbnn = a;
	}
         public Integer getsiparis() {
		return siparis;
	}

	public void setsiparis(Integer a) {
		this.siparis = a;
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekle;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField miktar;
    private javax.swing.JButton onay;
    private javax.swing.JTable tablo1;
    private javax.swing.JTextField tisbn;
    // End of variables declaration//GEN-END:variables
    private Integer isbnn;
    private Integer siparis;
}
