/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javaapplication3.mainJFrame.conn;
import static javaapplication3.mainJFrame.m;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.AWTEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication3.F1.kitaplar;
import static javaapplication3.F1.miktarlar;
/**
 *
 * @author nina
 */
public class SiparisEkle extends javax.swing.JFrame {

    /**
     * Creates new form SiparisEkle
     */DefaultTableModel dtm;
    public SiparisEkle() {
        initComponents();
        this.setLocationRelativeTo(null);
            dtm = (DefaultTableModel)tablo1.getModel();
        try {    dtm.setRowCount(0);
            String query2 = null;
            query2 = "SELECT * FROM kitaplar order by isim ";
            try (PreparedStatement pst = conn.prepareStatement(query2)) {
                 
                ResultSet r2 = pst.executeQuery();
                while (r2.next()){
                    String id = r2.getString(1);
                    String name = r2.getString(2);
                    String  mail = r2.getString(3);
                    
                    Object[] satir ={id, name, mail,null};
                    
                    dtm.addRow(satir);}
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
       
        //this.setisbnn(Integer.parseInt(dtm.getValueAt(isbn, 0).toString()));
        
        //String isimm = dtm.getValueAt(isbn, 1).toString();
        //int fiyatt = Integer.parseInt(dtm.getValueAt(isbn, 2).toString());
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablo1 = new javax.swing.JTable();
        miktar = new javax.swing.JTextField();
        onay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        tisbn = new javax.swing.JTextField();
        midd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tablo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ISBN", "Book", "Price"
            }
        ));
        tablo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablo1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo1);

        onay.setBackground(java.awt.Color.red);
        onay.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        onay.setForeground(java.awt.Color.black);
        onay.setText("Add");
        onay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onayActionPerformed(evt);
            }
        });

        jLabel1.setText("Amount");

        exit.setBackground(java.awt.Color.red);
        exit.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        exit.setForeground(java.awt.Color.black);
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        midd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middActionPerformed(evt);
            }
        });

        jLabel2.setText("MID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(onay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(midd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(onay)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onayActionPerformed
       String query4 = null;       
     
                      query4 ="insert into kitap_siparisi(sip,isbn,miktar,odate) values("+midd.getText()+","+getisbnn()+","+miktar.getText() +",'"+ LocalDate.now()
         .toString() +"')";
                System.out.println(query4);
                    try (PreparedStatement pst3 = conn.prepareStatement(query4)) {
                        boolean r4 = pst3.execute();
                        pst3.close();
                        
                    } catch (SQLException ex) {
             Logger.getLogger(SiparisEkle.class.getName()).log(Level.SEVERE, null, ex);
         }
        miktar.setText("");
        tisbn.setText("");
        midd.setText("");
        	           
    }//GEN-LAST:event_onayActionPerformed
    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
dispose();
        new F1().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
        //String isimm = dtm.getValueAt(isbn, 1).toString();
        //int fiyatt = Integer.parseInt(dtm.getValueAt(isbn, 2).toString());
         // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tablo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo1MouseClicked
        dtm = (DefaultTableModel)tablo1.getModel();
        int  SelectedRowIndex= tablo1.getSelectedRow();
       this.setisbnn(Integer.parseInt((String) dtm.getValueAt(SelectedRowIndex, 0)));
        System.out.println(getisbnn());
       tisbn.setText((String) dtm.getValueAt(SelectedRowIndex, 0));
       kitaplar.add(getisbnn());
       
    }//GEN-LAST:event_tablo1MouseClicked

    private void middActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisEkle().setVisible(true);
            }
        });
    }
  public Integer getisbnn() {
		return isbnn;
	}

	public void setisbnn(Integer a) {
		this.isbnn = a;
	}
         public Integer getsiparis() {
		return siparis;
	}

	public void setsiparis(Integer a) {
		this.siparis = a;
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField midd;
    private javax.swing.JTextField miktar;
    private javax.swing.JButton onay;
    private javax.swing.JTable tablo1;
    private javax.swing.JTextField tisbn;
    // End of variables declaration//GEN-END:variables
    private Integer isbnn;
    private Integer siparis;
}
